services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  mariadb:
    image: mariadb:10.6.14
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./sql/mariadb.cnf:/etc/mysql/mariadb.conf.d/mariadb.cnf
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  jobmanager:
    build: .
    container_name: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - AWS_ENDPOINT=http://minio:9000
      - AWS_PATH_STYLE_ACCESS=true
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./jobs/job.sql:/opt/flink/job.sql
    depends_on:
      - minio
    deploy:
          replicas: 1
  taskmanager:
    build: .
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password123
      - AWS_ENDPOINT=http://minio:9000
      - AWS_PATH_STYLE_ACCESS=true
    depends_on:
      - jobmanager
      - minio
    command: taskmanager
    deploy:
          replicas: 2

volumes:
  minio_data:
